// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistance;

#nullable disable

namespace Persistance.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    [Migration("20250705112407_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryID");

                    b.ToTable("tblCategory", (string)null);
                });

            modelBuilder.Entity("Entities.Movement", b =>
                {
                    b.Property<int>("MovementID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MovementID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FK_categoryID")
                        .HasColumnType("int");

                    b.Property<string>("GifFilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MovementID");

                    b.HasIndex("FK_categoryID");

                    b.ToTable("tblMovement", (string)null);
                });

            modelBuilder.Entity("Entities.Program", b =>
                {
                    b.Property<int>("ProgramID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProgramID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FK_CoachID")
                        .HasColumnType("int");

                    b.Property<int>("FK_StudentID")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProgramID");

                    b.HasIndex("FK_CoachID");

                    b.HasIndex("FK_StudentID");

                    b.ToTable("tblProgram", (string)null);
                });

            modelBuilder.Entity("Entities.ProgramDayMovement", b =>
                {
                    b.Property<int>("ProgramDayMovementID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProgramDayMovementID"));

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("int");

                    b.Property<int>("FK_MovementID")
                        .HasColumnType("int");

                    b.Property<int>("FK_ProgramDaysID")
                        .HasColumnType("int");

                    b.Property<string>("OrderInDay")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("Reps")
                        .HasColumnType("smallint");

                    b.Property<short>("Sets")
                        .HasColumnType("smallint");

                    b.HasKey("ProgramDayMovementID");

                    b.HasIndex("FK_MovementID");

                    b.HasIndex("FK_ProgramDaysID");

                    b.ToTable("tblProgramDayMovement", (string)null);
                });

            modelBuilder.Entity("Entities.ProgramDays", b =>
                {
                    b.Property<int>("ProgramDaysID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProgramDaysID"));

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FK_ProgramID")
                        .HasColumnType("int");

                    b.Property<bool>("IsRestDay")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProgramDaysID");

                    b.HasIndex("FK_ProgramID");

                    b.ToTable("tblProgramDays", (string)null);
                });

            modelBuilder.Entity("IDP.Entities.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EducationDegree")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("Gender")
                        .HasColumnType("bit");

                    b.Property<double?>("Height")
                        .HasColumnType("float");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Target")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Entities.Movement", b =>
                {
                    b.HasOne("Entities.Category", "category")
                        .WithMany("movements")
                        .HasForeignKey("FK_categoryID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("category");
                });

            modelBuilder.Entity("Entities.Program", b =>
                {
                    b.HasOne("IDP.Entities.ApplicationUser", "Coach")
                        .WithMany("ProgramCoachStudentsAsCoach")
                        .HasForeignKey("FK_CoachID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IDP.Entities.ApplicationUser", "Student")
                        .WithMany("ProgramCoachStudentsAsStudent")
                        .HasForeignKey("FK_StudentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Coach");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Entities.ProgramDayMovement", b =>
                {
                    b.HasOne("Entities.Movement", "Movement")
                        .WithMany("ProgramDayMovement")
                        .HasForeignKey("FK_MovementID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Entities.ProgramDays", "ProgramDays")
                        .WithMany("ProgramDayMovement")
                        .HasForeignKey("FK_ProgramDaysID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Movement");

                    b.Navigation("ProgramDays");
                });

            modelBuilder.Entity("Entities.ProgramDays", b =>
                {
                    b.HasOne("Entities.Program", "Program")
                        .WithMany("ProgramDays")
                        .HasForeignKey("FK_ProgramID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Program");
                });

            modelBuilder.Entity("Entities.Category", b =>
                {
                    b.Navigation("movements");
                });

            modelBuilder.Entity("Entities.Movement", b =>
                {
                    b.Navigation("ProgramDayMovement");
                });

            modelBuilder.Entity("Entities.Program", b =>
                {
                    b.Navigation("ProgramDays");
                });

            modelBuilder.Entity("Entities.ProgramDays", b =>
                {
                    b.Navigation("ProgramDayMovement");
                });

            modelBuilder.Entity("IDP.Entities.ApplicationUser", b =>
                {
                    b.Navigation("ProgramCoachStudentsAsCoach");

                    b.Navigation("ProgramCoachStudentsAsStudent");
                });
#pragma warning restore 612, 618
        }
    }
}
